import { IDropdownOption } from "@/types/global/dropdownOption";
import { IFormInput } from "@/types/global/formInput";
import { AppDispatch } from "@/redux/store";
import { setOpenExpenditureModel } from "@/redux/reducer/pageConfigReducer";
import { ColumnDef } from "@tanstack/react-table";
import { statusColor } from "./theme";

export const tableHeader: ColumnDef<any, any>[] = [
  {
    accessorKey: "expenditureName",
    header: "Expenditure",
  },
  {
    accessorKey: "expenseId",
    header: "Claim ID",
  },
  {
    accessorKey: "totalAmount",
    header: "Amount Claimed",
  },
  {
    accessorKey: "paymentStatus",
    header: "Amount Status",
    cell: ({ row }) => {
      const status = row.original.paymentStatus;
      const color = statusColor[status];
      const textClass = `text-${color}`;
      const borderClass = `border-${color}`;

      const _class = `${textClass} ${borderClass} border-1 py-2 px-5 border-solid rounded-full`;

      return <p className={_class}>{status}</p>;
    },
  },
  {
    accessorKey: "remark",
    header: "Manager's Comments",
  },
];

export const sampleExpenseData = [
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
  {
    expenseId: "012",
    employeeId: "1234",
    employeeFirstName: "abc",
    employeeLastName: "xyz",
    reimbursementDate: "2024-01-01",
    totalAmount: "100",
    totalAmountClaimed: 100,
    statusByManager: "Approved",
    statusByAccManager: "Pending",
    paymentStatus: "Rejected",
    remark: "This expense is related to the campaign happened in ITC",
    expenditureName: "This expense is related to the campaign happened in ITC",
    expenditureSubmittedDate: "2024-01-01",
    createdByUserID: "1234",
    createdAtTime: "2024-01-01T10:01:01",
    createdAtDate: "2024-01-01",
    updatedByUserID: "1234",
    updatedAtTime: "2024-01-01T10:01:01",
    updatedAtDate: "2024-01-01",
  },
];

export const filterForm: IFormInput[] = [
  {
    type: "date",
    placeholder: "Select date",
    name: "startDate",
  },
];

export const menuOption: IDropdownOption[] = [
  {
    icon: "/icons/eye.svg",
    action: (dispatch: AppDispatch) =>
      dispatch(setOpenExpenditureModel({ status: true, type: "View" })),
  },
  {
    icon: "/icons/edit.svg",
    action: (dispatch: AppDispatch) =>
      dispatch(setOpenExpenditureModel({ status: true, type: "Edit" })),
  },
];
